name: First pipeline
on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
  steps: 
    -name: checkout code 
     uses: actions/checkout@v2  #this is an action that is re-useable and it was provided by github
    -name: run test
      run: echo Hello world