name: First pipeline
on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
  steps: 
    - name: checkout code 
     uses: actions/checkout@v2  
    - name: run test
      run: echo Hello world