name: Secrets 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: run a secret 
      run: echo "This is my secret ${{ secrets.MY_SECRETS}}"