name: Secrets 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: run a secret 
      run: echo "This is my secret ${{ secrets.MY_SECRETS}}"

    - name: runn an env as a secret
      run: echo "This is my secret $secret"

    - env:
      secret: echo "This is the secret ${{ secrets.MY_SECRETS}}"